### ISSUE TITLE
Head pose in Interaction_Streams_103

### ISSUE THREAD

**Issue by mostlyjason** [Tobii/CoreSDK#1]
Hi I'm trying out the latest core SDK, which I'm told is currently in beta? I'm really interested in trying the head pose sample in Interaction_Streams_103. I ran it and was able to get all the streams working except for the head pose stream. I'm using version 2.8.0 with the beta features setting enabled. Is the head pose data currently supported by my version, or do I need to wait for an update?

**Comment by dennyronngren** [comment]
Hi Jason, sorry for the delay in replying and the sample not working. Head tracking is not supported in the Core SDK with 2.8.0, it requires an updated core eye tracking package that is not released to the public yet. No firm release date yet, but you shouldn't have to wait long ;-)

**Comment by dennyronngren** [comment]
@mostlyjason , our Tobii Eye Tracking Core Software (2.9.0) that supports head tracking through Core SDK is now released. Check for updates in your installation and then 2.9.0 should show up, and the sample should be working as expected :-)

**Comment by vdecine** [comment]
Hi,
 I am using version 2.13.4 of the Tobii Eye Tracking Core Software but have the same issue described above: the callback for headpose data is never called. Any hints?
